#!/usr/bin/env bash

APP=`node -e "console.log(require('./package.json').name);"`
BIN=node_modules/.bin
DST=${1:-./public/$APP}
SRC=${2:-.}

echo "[pacpan] constantly packaging app ${APP} at ${SRC} to ${DST}..."

mkdir -p playground

$BIN/watchify --debug --verbose \
  --external panels-ui \
  --external react \
  --external react-redux \
  --external redux \
  --external redux-logger \
  --external redux-thunk \
  --ignore **/node_modules/**,**/__tests__/** \
  --require $SRC/index:$APP \
  --extension .es6 \
  --plugin browserify-hmr \
  --transform babelify \
  --outfile $DST.dev.js
